// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJN_OqNvbKpyP3yVy7vqCP3-mAfRwgTfs',
    appId: '1:292086085865:web:1b8e1073064dad47ce9878',
    messagingSenderId: '292086085865',
    projectId: 'skillsync-77bc4',
    authDomain: 'skillsync-77bc4.firebaseapp.com',
    storageBucket: 'skillsync-77bc4.firebasestorage.app',
    measurementId: 'G-P23WVPELEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWe9kZOlaq2NYJkNmwSd0hhlh_MLZRLmg',
    appId: '1:292086085865:android:f2937bc695102ecdce9878',
    messagingSenderId: '292086085865',
    projectId: 'skillsync-77bc4',
    storageBucket: 'skillsync-77bc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpftwGcYb13SlaGEfRj4LngFjeyPXd0xA',
    appId: '1:292086085865:ios:603850c64f077cface9878',
    messagingSenderId: '292086085865',
    projectId: 'skillsync-77bc4',
    storageBucket: 'skillsync-77bc4.firebasestorage.app',
    iosBundleId: 'com.example.skillsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpftwGcYb13SlaGEfRj4LngFjeyPXd0xA',
    appId: '1:292086085865:ios:603850c64f077cface9878',
    messagingSenderId: '292086085865',
    projectId: 'skillsync-77bc4',
    storageBucket: 'skillsync-77bc4.firebasestorage.app',
    iosBundleId: 'com.example.skillsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJN_OqNvbKpyP3yVy7vqCP3-mAfRwgTfs',
    appId: '1:292086085865:web:676ee50618b40561ce9878',
    messagingSenderId: '292086085865',
    projectId: 'skillsync-77bc4',
    authDomain: 'skillsync-77bc4.firebaseapp.com',
    storageBucket: 'skillsync-77bc4.firebasestorage.app',
    measurementId: 'G-K0N48PT4C4',
  );
}
